102 patch create edit profile routes
GSG-G13/Balanty pull request #103
Opened 2023-06-27 00:12 UTC by alaaahmade

102 patch create edit profile routes #102

2023-07-01 09:36 UTC, Saeed99Madi approved these changes
Great Work Alaa @alaaahmade

2023-07-02 17:41 UTC, ahmedirheem requested changes

2023-07-02 17:41 UTC, ahmedirheem commented on server/services/stadiums.ts
> +      status: 401,
404 is the status of not found

2023-07-02 17:41 UTC, ahmedirheem commented on server/services/stadiums.ts
> +    data: galleries,
galleries consist of two things, the number of updated rows and the updated values itself, and here we just need updated values itself

2023-07-02 17:41 UTC, ahmedirheem commented on server/services/stadiums.ts
> +      status: 401,
404 is the status of not found

2023-07-02 17:41 UTC, ahmedirheem commented on server/services/stadiums.ts
> +  return { status: 204, data: result };
`result` here is the number of deleted rows, what the benefit from it to send it in the response

2023-07-03 09:20 UTC, ahmedirheem approved these changes
Good Job Alaa

2023-07-03 09:34 UTC, Emanalabsi requested changes

2023-07-03 09:34 UTC, Emanalabsi commented on server/controllers/stadiums.ts
>  import { RequestHandler, Request, Response } from 'express';
move this to the top

2023-07-03 09:34 UTC, Emanalabsi commented on server/controllers/stadiums.ts
>    req: Request,
where is res: response! how it worked?

2023-07-03 09:34 UTC, Emanalabsi commented on server/controllers/stadiums.ts
> +  res.status(response.status).json(response);
response?.status, there might be no response status

2023-07-03 10:03 UTC, Emanalabsi approved these changes

2023-07-03 10:03 UTC, merged