84 create edit functionality
GSG-G13/Balanty pull request #104
Opened 2023-06-27 00:14 UTC by alaaahmade

84 create edit functionality #84

2023-07-02 12:17 UTC, Saeed99Madi approved these changes
awesome @alaaahmade

2023-07-03 09:41 UTC, Emanalabsi approved these changes

2023-07-03 10:19 UTC, ahmedirheem requested changes
Edit the style: - make a space between slider and calender

2023-07-03 10:55 UTC, alaaahmade commented on client/src/components/stadiumProfile/DeleteDialog.tsx
> +      await axios.delete(`/api/v1/stadiums/gallery/${ImageId}/${StadiumId}`);
Based on the provided code, if the HandleAgree function is only used within the DeleteDialog component and it doesn't need to be accessed or shared by other components, it is generally better to keep it within the component itself. There is no need to include it in a context or externalize it unless there is a specific reason or requirement to do so.

Keeping the function within the component helps with encapsulation and improves code readability and maintainability. It keeps the function scoped to the component where it's used, making it easier to understand and reason about the behavior of the component.

If the HandleAgree function doesn't need to be accessed or shared outside of the DeleteDialog component, you can leave it as it is in the component code.

2023-07-03 11:22 UTC, ahmedirheem approved these changes

2023-07-03 11:23 UTC, merged