113 player page
GSG-G13/Balanty pull request #115
Opened 2023-07-02 10:05 UTC by Emanalabsi

2023-07-02 11:10 UTC, alaaahmade requested changes

2023-07-02 11:10 UTC, alaaahmade commented on client/src/components/playerProfile/PlayerFollows.tsx
> +    <Card
create A styled component for this element

2023-07-02 11:10 UTC, alaaahmade commented on client/src/components/playerProfile/PlayerFollows.tsx
> +      <Button
create A styled component for this element  also

2023-07-02 11:10 UTC, alaaahmade commented on client/src/components/playerProfile/test.ts
> +// import React, { ReactElement, useState } from 'react';
remove this file

2023-07-04 13:50 UTC, alaaahmade approved these changes

2023-07-04 14:34 UTC, ahmedirheem approved these changes

2023-07-04 17:22 UTC, Saeed99Madi approved these changes

2023-07-05 10:21 UTC, merged