122 get players
GSG-G13/Balanty pull request #134
Opened 2023-07-04 12:04 UTC by Emanalabsi

2023-07-04 15:03 UTC, ahmedirheem approved these changes
Great job Eman 🤞

2023-07-04 17:49 UTC, Saeed99Madi requested changes

2023-07-04 17:49 UTC, Saeed99Madi commented on server/services/player.ts
> +    status: 201,
201 !! and static status !!!

2023-07-04 17:49 UTC, Saeed99Madi commented on server/routes/player.ts
> +playerRouter.post('/:page', errorWrapper(getPlayers));
get players needs to be GET Method

2023-07-05 19:43 UTC, alaaahmade approved these changes

2023-07-05 20:52 UTC, Saeed99Madi approved these changes
Great Work but it will be better if you made some tests

2023-07-05 21:00 UTC, merged