154 chat socket
GSG-G13/Balanty pull request #169
Opened 2023-07-07 21:44 UTC by ahmedirheem

2023-07-08 11:59 UTC, Emanalabsi approved these changes

2023-07-08 12:05 UTC, Emanalabsi commented
Keep up the fantastic work! I eagerly anticipate witnessing the incredible things you'll achieve as you continue on your path of excellence.

2023-07-08 12:23 UTC, ahmedirheem commented
> Keep up the fantastic work! I eagerly anticipate witnessing the incredible things you'll achieve as you continue on your path of excellence.

2023-07-08 16:05 UTC, Saeed99Madi approved these changes

2023-07-08 19:43 UTC, alaaahmade requested changes

2023-07-08 19:43 UTC, alaaahmade commented on server/models/Message.ts
> +  id: any;
dont use ```any``` for types

2023-07-09 11:50 UTC, alaaahmade approved these changes

2023-07-09 11:50 UTC, merged