create model review
GSG-G13/Balanty pull request #22
Opened 2023-06-12 12:27 UTC by Heba-Adwan

create model review

2023-06-12 13:01 UTC, Saeed99Madi requested changes

2023-06-12 13:01 UTC, Saeed99Madi commented on server/models/Review.ts
Great Job and its right,
But needs to add a new column that contain the value of review.

2023-06-12 18:26 UTC, alaaahmade approved these changes

2023-06-12 18:38 UTC, Saeed99Madi approved these changes
Well Done Heba @Heba-Adwan

2023-06-13 11:04 UTC, Emanalabsi approved these changes

2023-06-13 11:05 UTC, merged