17 create messages model
GSG-G13/Balanty pull request #23
Opened 2023-06-12 12:28 UTC by ahmedirheem

2023-06-12 12:51 UTC, Saeed99Madi approved these changes
good job

2023-06-12 13:16 UTC, alaaahmade requested changes

2023-06-12 13:16 UTC, alaaahmade commented on server/models/messages.ts
> +  declare id: number;
remove id column
id column will be added by default on sequelize

2023-06-12 13:16 UTC, alaaahmade commented on server/models/messages.ts
> +    id: {
remove id column
id column will be added by default on sequelize

2023-06-12 13:16 UTC, alaaahmade commented on server/models/messages.ts
> +    player_id: {
player_id should have references to be Foreign Key

like :  player_id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'Player',
        key: 'id',
      },

2023-06-12 13:16 UTC, alaaahmade commented on server/models/messages.ts
> +      autoIncrement: true,
remove autoIncrement from player_id because it's a foreign key

2023-06-12 13:16 UTC, alaaahmade commented on server/models/messages.ts
> +      autoIncrement: true,
remove autoIncrement from player_id because it's a foreign key

2023-06-13 08:13 UTC, Saeed99Madi commented
No Description Provided !!

2023-06-13 09:09 UTC, Saeed99Madi approved these changes
Great Job Ahmed @ahmedirheem 
:100:

2023-06-13 10:43 UTC, alaaahmad123 approved these changes

2023-06-13 10:44 UTC, alaaahmade approved these changes

2023-06-13 11:07 UTC, Heba-Adwan approved these changes

2023-06-13 11:27 UTC, merged