25 create best stadiums section
GSG-G13/Balanty pull request #41
Opened 2023-06-14 04:00 UTC by ahmedirheem

related #25

2023-06-14 11:46 UTC, Saeed99Madi requested changes
Great Job Ahmed, Just needs to use the styled function that supported from MUI,

2023-06-14 13:36 UTC, Emanalabsi approved these changes

2023-06-14 15:25 UTC, alaaahmade requested changes

2023-06-14 15:25 UTC, alaaahmade commented on client/src/components/best-stadiums/BestStadiums.tsx
> +const BestStadiums: FC = () => {
done forget add type of returning function : ReactElement

2023-06-14 15:25 UTC, alaaahmade commented on client/src/components/best-stadiums/BestStadiums.tsx
> +const BestStadiums: FC = () => {
done forget to add the type of returning function : ReactElement

2023-06-14 15:25 UTC, alaaahmade commented on client/src/components/best-stadiums/BestStadiums.tsx
> +const BestStadiums: FC = () => {
done forget add type of returning function : ReactElement

2023-06-14 15:25 UTC, alaaahmade commented on client/src/components/best-stadiums/Stadium.tsx
> +const Stadium: FC<Props> = ({ image, name, rate, address, description }) => {
done forget to add the type of returning function : ReactElement

2023-06-14 18:48 UTC, alaaahmade approved these changes
great job dear Ahmed

2023-06-15 19:08 UTC, Heba-Adwan commented
solve conflict

2023-06-16 07:58 UTC, Heba-Adwan approved these changes

2023-06-16 09:14 UTC, Saeed99Madi approved these changes

2023-06-16 12:21 UTC, merged