build: create contact us component and make styled component
GSG-G13/Balanty pull request #42
Opened 2023-06-14 06:40 UTC by Heba-Adwan

create contact us component and make styled component

2023-06-14 11:38 UTC, Saeed99Madi approved these changes

2023-06-14 11:38 UTC, Saeed99Madi commented
Great Job Heba @Heba-Adwan

2023-06-14 11:39 UTC, Saeed99Madi commented
Don't Work in tow GitHub Accounts !!!!!!

2023-06-14 17:56 UTC, ahmedirheem requested changes
You must resolve conflict
`ContactUsStyledComponent.tsx` file must be named as ContactUs.styled.tsx, and the same for other styled files.

2023-06-15 13:09 UTC, Emanalabsi approved these changes

2023-06-15 13:12 UTC, ahmedirheem approved these changes

2023-06-15 13:12 UTC, merged