build: definition who we are and styled mui
GSG-G13/Balanty pull request #43
Opened 2023-06-14 07:54 UTC by Heba-Adwan

definition who we are and styled mui

2023-06-14 11:35 UTC, Saeed99Madi requested changes
Great Job Hebe its looks you are professional, Just needs to remove the comment code

2023-06-14 11:35 UTC, Saeed99Madi commented on client/src/components/Definition.tsx
> +
remove the comment code

2023-06-14 13:29 UTC, Emanalabsi approved these changes

2023-06-14 18:37 UTC, ahmedirheem requested changes
For better file structure you must add the Component and its style in the same folder with the name of the component
for example:
-header|
             |-Header.tsx
             |-Header.styled.tsx

2023-06-15 14:54 UTC, alaaahmade approved these changes

2023-06-15 16:18 UTC, alaaahmade requested changes

2023-06-15 16:18 UTC, alaaahmade commented on client/src/components/Definition/DefinitionSection.tsx
> +import {
there is no index.ts file to import styled component from it

2023-06-15 16:51 UTC, alaaahmade approved these changes

2023-06-15 18:29 UTC, ahmedirheem approved these changes

2023-06-15 18:30 UTC, merged