build: create Features of Balanty
GSG-G13/Balanty pull request #45
Opened 2023-06-14 13:38 UTC by Heba-Adwan

create Features of Balanty #27

2023-06-14 13:41 UTC, Emanalabsi approved these changes

2023-06-14 15:39 UTC, alaaahmade requested changes

2023-06-14 15:39 UTC, alaaahmade commented on client/src/components/Features.tsx
> +} from './index';
There is nothing exported from index.ts

2023-06-14 15:39 UTC, alaaahmade commented on client/src/components/Features.tsx
> +
Separate every React Component with a special file

2023-06-14 15:39 UTC, alaaahmade commented on client/src/components/styledRootComponent/FeaturesStyledComponent.tsx
> +export const StyledBoxFeatures = styled.div`
We want to use the styled component provided by Mui

2023-06-14 15:39 UTC, alaaahmade requested changes

2023-06-14 15:39 UTC, alaaahmade commented on client/src/components/Features.tsx
> +const FeatureSection: React.FC<FeatureProps> = ({ imageSrc, description }) => {
done forget to add the type of returning function : ReactElement

2023-06-14 15:39 UTC, alaaahmade commented on client/src/components/Features.tsx
> +const Feature: React.FC = () => {
done forget to add the type of returning function : ReactElement

2023-06-14 15:41 UTC, alaaahmade requested changes

2023-06-14 15:41 UTC, alaaahmade commented on client/src/components/Features.tsx
> +const FeatureSection: React.FC<FeatureProps> = ({ imageSrc, description }) => {
Separate every React Component with a special file

2023-06-15 08:28 UTC, Saeed99Madi approved these changes

2023-06-15 18:30 UTC, ahmedirheem approved these changes

2023-06-15 18:31 UTC, merged