53 build create match router
GSG-G13/Balanty pull request #59
Opened 2023-06-16 16:05 UTC by alaaahmade

53 build create match router: #53

2023-06-18 08:47 UTC, Saeed99Madi requested changes
## Take in consideration : 
- Make create match functionality validate if there any Scheduling conflict.
- follow this route naming convention :
```
matchRouter.get('/matches', errorWrapper(controller));
matchRouter.post('/matches', errorWrapper(controller));
matchRouter.put('/matches', errorWrapper(controller));
matchRouter.get('/matches/:id', errorWrapper(controller));
```

2023-06-20 09:45 UTC, Saeed99Madi requested changes
Very good Effort but there is some notes

2023-06-20 09:45 UTC, Saeed99Madi commented on server/controllers/matches.ts
> +  req.userData = { owner_id: 3 };
this line is not necessary,

2023-06-20 09:45 UTC, Saeed99Madi commented on server/services/matches.ts
> +  return '! هذا الوقت محجوز';
what if the stadiumId is not correct it will return the same Error Message, and this not Good

2023-06-20 12:16 UTC, Saeed99Madi commented
tests Failed @alaaahmade

2023-06-21 01:53 UTC, ahmedirheem approved these changes

2023-06-21 07:32 UTC, Emanalabsi approved these changes

2023-06-21 07:32 UTC, Saeed99Madi approved these changes
Well Done @alaaahmade

2023-06-21 07:33 UTC, merged