89 stadium profile
GSG-G13/Balanty pull request #90
Opened 2023-06-24 14:06 UTC by alaaahmade

89 Stadium profile #89

2023-06-25 16:41 UTC, Saeed99Madi approved these changes

2023-06-26 08:49 UTC, ahmedirheem approved these changes

2023-06-26 08:56 UTC, Emanalabsi requested changes

2023-06-26 08:56 UTC, Emanalabsi commented on server/services/matches.ts
>    const ExisteStadium = await Stadium.findOne({ where: { UserId: StadiumId } });
isStadiumExist indicates more to the purpose

2023-06-26 10:57 UTC, Emanalabsi approved these changes

2023-06-26 10:57 UTC, merged