85 match room chat back
GSG-G13/Balanty pull request #94
Opened 2023-06-25 13:53 UTC by ahmedirheem

relates #85

2023-06-25 16:15 UTC, Saeed99Madi requested changes

2023-06-25 16:15 UTC, Saeed99Madi commented on server/services/matchChat.ts
> +
You must take in consederation the not happy reults in your services, like returning no messages, in this case you need to return message means that there is no any messages! 
and return this form of response from the service : 
```
//in failure case  
return {
      status: errorStatue[ex: 404],
      data: ''no messages !",
    };
    //in success case  
return {
      status: success Status [ex:  200],
      data: result,
    };

```  
   and handle it in the controller in this way : 
   
```
 const data = (await yourService(req));

  res.status(data.status).json(data);
```
  
  this way will help you also to send the right status and clear response for the frontEnd Side
  
 ### Note : 
  - take in consideration that make this in all services and controllers

2023-06-25 16:15 UTC, Saeed99Madi commented on server/routes/matchChat.ts
> +chatRouter.post('/add', addMessage);
`chatRouter.post('/add', addMessage);`
`add` not necessary 
for best practice to in router naming convention 
`chatRouter.post('/', addMessage);`

2023-06-25 16:53 UTC, alaaahmade requested changes

2023-06-25 16:53 UTC, alaaahmade commented on server/controllers/matchChat.ts
> +const addMessage = async (req: Request, res: Response) => {
this controller missing types and returning types :
addMessage: RequestHandler = (): Promises<Void> =>

2023-06-25 16:53 UTC, alaaahmade commented on server/controllers/matchChat.ts
> +const getMessageById = async (req: Request, res: Response) => {
also this controller missing types
and all controllers on this file

2023-06-25 16:53 UTC, alaaahmade commented on server/controllers/matchChat.ts
> +const deleteMessage = async (req: Request, res: Response) => {
and this controller missing types

2023-06-25 16:53 UTC, alaaahmade commented on server/services/matchChat.ts
> +const addMessageService = async ({
add the returning types for all services on this file: Promise<{
"your types for the response object"
}>

2023-06-26 08:22 UTC, Saeed99Madi approved these changes

2023-06-26 12:54 UTC, Emanalabsi commented on server/controllers/matchChat.ts
> +  const data = await editMessageService(id, newMessage);
updatedMessage would be more descriptive

2023-06-26 13:00 UTC, Emanalabsi approved these changes

2023-06-26 13:02 UTC, alaaahmade approved these changes

2023-06-26 16:39 UTC, merged